name: SemigroupViz
version: 1.0.0
date: 2019-03-21
description: |
    Visualization Tools for Semigroups

authors:
    - name: Nathan Carter
      url: http://nathancarter.github.io

maintainers:
    - name: Nathan Carter
      url: http://nathancarter.github.io

GAP: ">= 4.9"

needed-pkgs:
    - name: "JupyterViz"
      version: "1.5.1"
      url: "https://nathancarter.github.io/jupyterviz"
    - name: "semigroups"
      version: "3.0.20"
      url: "https://gap-packages.github.io/Semigroups"
    - name: "GAPDoc"
      version: "1.3"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://nathancarter.github.io/semigroupviz
readme: README.md
packageinfo: https://nathancarter.github.io/semigroupviz/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/nathancarter/semigroupviz/releases/download/v1.0.0/semigroupviz-1.0.0.tar.gz

abstract: |
    The <span class="pkgname">SemigroupViz</span> package    adds visualization tools for semigroups to GAP.    These can be used in Jupyter notebooks or from the GAP REPL.

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    Semigroups, visualization, Green's relations, egg-box diagram, HTML.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Car19</span>]   <b class='BibAuthor'>Carter, N.</b>,
     <i class='BibTitle'>SemigroupViz, Visualization Tools for Semigroups,
             Version 1.0.0</i>
     (<span class='BibYear'>2019</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://nathancarter.github.io/semigroupviz">https://nathancarter.github.io/semigroupviz</a></span>.
    </p>
    

bibtex: |
    @misc{ SemigroupViz1.0.0,
      author =           {Carter, N.},
      title =            {{SemigroupViz},   Visualization   Tools  for
                          Semigroups, {V}ersion 1.0.0},
      month =            {Mar},
      year =             {2019},
      note =             {GAP package},
      howpublished =     {\href
                          {https://nathancarter.github.io/semigroupviz}
                          {\texttt{https://nathancarter.github.io/}\discretionary
                          {}{}{}\texttt{semigroupviz}}},
      keywords =         {Semigroups;      visualization;      Green's
                          relations; egg-box diagram; HTML},
      printedkey =       {Car19}
    }

