#!
#! @Chapter Cayley Graphs
#! @ChapterLabel cayley
#!
#! @Section Preliminaries: Semigroups acting on themselves
#!
#! A semigroup <Math>S</Math> can be said to act on itself by right multiplication
#! if we associate with any element <Math>s\in S</Math> a function
#! <Math>f_s:S\to S</Math> that performs right multiplication by the element
#! <Math>s</Math>, that is, <Math>f(t)=ts</Math>.  Similarly, a semigroup can act
#! on itself by left multiplication if with any given <Math>s\in S</Math> we
#! associate a function <Math>f_s(t)=st</Math>.
#!
#! For now, we will discuss actions only by right multiplication.
#!
#! If <Math>S</Math> is a group, each of these functions (or "actions") is a
#! permutation, and is thus often written <Math>\phi_s</Math> rather than
#! <Math>f_s</Math>.
#!
#! We can illustrate any <Math>f_s</Math> by considering the elements of
#! <Math>S</Math> as the vertices in a graph and letting there be an edge
#! between two elements <Math>t,t'\in S</Math> if and only if
#! <Math>f_s(t)=t'</Math>.  Such a graph draws an arrow from each
#! <Math>t</Math> to its image <Math>t'</Math> under <Math>f_s</Math>.
#!
#! If we have a set of elements <Math>\left\{ s_1,\ldots,s_n \right\}</Math>,
#! we can illustrate all the actions <Math>f_{s_1},\ldots,f_{s_n}</Math> on
#! one graph by keeping the same vertex set (all elements of <Math>S</Math>)
#! and letting there be a different set of edges for each <Math>f_{s_i}</Math>.
#! Typically we distinguish the edge sets by assigning each a different color,
#! and then it is possible to draw them all on the same graph and still
#! distinguish them.
#!
#! If we choose <Math>\left\{ s_1,\ldots,s_n \right\}</Math> to be a
#! generating set for the semigroup, then the resulting graph will be
#! connected.  (In fact, in many cases, a proper subset of the generators will
#! ensure that the graph is connected.)
#!
#! @Section Generating Cayley graphs
#! @SectionLabel makecd
#!
#! As an example, consider the semigroup of non-invertible transformations
#! generated by the six idempotents of degree 3 and rank 2,
#! which you can compute with the following &GAP; code.
#!
#! @Example
#! LoadPackage( "semigroups" );
#! S := SingularTransformationSemigroup( 3 );
#! @EndExample
#!
#! A Cayley graph of this semigroup can be connected with just two generators.
#! Generating that diagram using one of the tools from this package yields the
#! following result.
#!
#! <Alt Only="LaTeX">
#!     \begin{center}
#!         \includegraphics[height=3in]{sgp-S3-unorg.png}
#!     \end{center}
#! </Alt>
#! <Alt Only="HTML"><![CDATA[<center><img height="550" src="sgp-S3-unorg.png"/></center>]]></Alt>
#! <Alt Not="LaTeX HTML">Image of a Cayley graph not available in this medium.</Alt>
#!
#! In section <Ref Sect="Section_interact2"/> we will cover how to organize
#! such diagrams better.
#!
#! You can optionally include labels for each edge in the diagram as well,
#! although this can often make it quite cluttered, so it is disabled by
#! default.  (See the options for <Ref Func="ShowCayleyGraph"/> for
#! details.)  But it is also possible to infer the elements from the graph
#! in two different ways.
#! <List>
#!   <Item>For many semigroups, it will be obvious which element is
#!     represented by each color, because there is only one element in the
#!     semigroup that could act on the semigroup's elements in the way
#!     shown by the arrows in question.  (This is always true in groups,
#!     but is not true for some elements of some semigroups.)</Item>
#!   <Item>If you provided a generators list when generating the semigroup,
#!     those generators were assigned colors evenly spaced along the
#!     color spectrum, in increasing frequencies (red first, violet last).
#!     So the red generator is always first, the second will usually be
#!     green or greenish blue, and so on.</Item>
#! </List>
#! When in doubt, simply regenerate the diagram with the option enabled
#! to show the names of the elements on each edge.
#!
#! If the semigroup is sufficiently large, attempting to create a
#! Cayley graph will tend to lead to an image so busy with vertices and
#! edges that the viewer cannot take any useful information from it.  The
#! typical limit is somewhere around 100 elements.  For instance, the
#! following Cayley graph of a semigroup with 256 elements is almost
#! completely useless due to the number of visual elements present.
#!
#! <Alt Only="LaTeX">
#!     \begin{center}
#!         \includegraphics[height=3in]{sgp-F4-unorg.png}
#!     \end{center}
#! </Alt>
#! <Alt Only="HTML"><![CDATA[<center><img height="550" src="sgp-F4-unorg.png"/></center>]]></Alt>
#! <Alt Not="LaTeX HTML">Image of a Cayley graph not available in this medium.</Alt>
#!
#! @Section Formatting element names
#!
#! If the elements of your semigroup have a compact representation,
#! then the <Ref Func="ShowCayleyGraph"/> function introduced in Section
#! <Ref Sect="Section_makecd"/> will produce readable graphs.
#! But if the elements of the semigroup have very long names, then the
#! text at each vertex of the graph will clutter the graph and make its
#! structure less apparent (and the overall result less attractive).
#!
#! To solve this problem, you can provide a function that maps elements
#! of your semigroup to whatever (typically more compact) notation you'd
#! like to use in the diagram.  You pass this as one of the options to
#! <Ref Func="ShowCayleyGraph"/>, under the name <Code>ToString</Code>.
#!
#! An example appears in Section <Ref Sect="Section_eltnames"/>, where the
#! same option is documented for <Ref Func="ShowEggBoxDiagram"/>.
#!
#! Detailed documentation of all the options of the
#! <Ref Func="ShowCayleyGraph"/> function can be found in its documentation
#! in Section <Ref Chap="Chapter_funcref"/>.
#!
#! @Section Interacting with Cayley graphs
#! @SectionLabel interact2
#!
#! The <Package>SemigroupViz</Package> package uses the
#! <URL Text="Cytoscape">http://www.cytoscape.org/</URL> graph-drawing
#! library to render Cayley graphs.  You can interact with them in any of
#! the ways provided by that library, including:
#! <List>
#!   <Item>Click and drag a vertex to reposition it.</Item>
#!   <Item>Click a vertex to select it, then Shift-Click or Control-Click
#!     (Command-Click on Mac) other vertices to add to the selection.
#!     Drag the entire selection to reposition it.  Click on the
#!     background to deselect.</Item>
#!   <Item>Use the mouse wheel to zoom in or out.</Item>
#!   <Item>Click and drag on the background to reposition the entire
#!     graph.</Item>
#!   <Item>Shift-Click or Control-Click (Command-Click on Mac) on the
#!     background and drag to create a selection rectangle to select a
#!     group of vertices.  Reposition/unselect as described above.</Item>
#! </List>
#!
#! This package does not contain any mechanism for creating aesthetically
#! pleasing Cayley graph layouts.  Cytoscape automatically lays out the
#! graph in a way that is somewhat balanced, but there is typically much
#! more symmetry inherent in a semigroup than cytoscape's default layout
#! makes evident.  Consider the following examples.
#!
#! @Subsection A singular transformation semigroup
#!
#! @Example
#! LoadPackage( "semigroupviz" );
#! S := SingularTransformationSemigroup( 3 );
#! compact := x ->
#!     ReplacedString( String( ListTransformation( x ) ), " ", "" );
#! ShowCayleyGraph( S, rec( ToString := compact ) );
#! @EndExample
#!
#! This produces the rather disorganized figure shown in Section
#! <Ref Sect="Section_makecd"/>.  But if we put in some manual effort to
#! drag the nodes around, we can often find a more aesthetically
#! pleasing arrangement of them.
#!
#! <Alt Only="LaTeX">
#!     \begin{center}
#!         \includegraphics[height=3.5in]{sgp-S3-org.png}
#!     \end{center}
#! </Alt>
#! <Alt Only="HTML"><![CDATA[<center><img height="650" src="sgp-S3-org.png"/></center>]]></Alt>
#! <Alt Not="LaTeX HTML">Image of a Cayley graph not available in this medium.</Alt>
#!
#! @Subsection An abelian group
#!
#! @Example
#! P := DirectProduct(
#!     Semigroup( [ Transformation( [ 2, 3, 1 ] ) ] ), # group Z_3
#!     Semigroup( [ Transformation( [ 3, 5, 4, 2, 6, 3 ] ) ] ) # group Z_5
#! ); # group Z_3 x Z_5
#! ShowCayleyGraph( P, rec( ToString := compact ) );
#! @EndExample
#!
#! This produces the following somewhat organized initial image due to the
#! inherent symmetry in the Cayley graphs of groups.
#!
#! <Alt Only="LaTeX">
#!     \begin{center}
#!         \includegraphics[height=2.4in]{sgp-P3-unorg.png}
#!     \end{center}
#! </Alt>
#! <Alt Only="HTML"><![CDATA[<center><img height="450" src="sgp-P3-unorg.png"/></center>]]></Alt>
#! <Alt Not="LaTeX HTML">Image of a Cayley graph not available in this medium.</Alt>
#!
#! But even so, we can still make it more attractive (sometimes in more than
#! one way) by rearranging the vertices, as shown in the following images.
#!
#! <Alt Only="LaTeX">
#!     \begin{center}
#!         \includegraphics[height=2.4in]{sgp-P3-org.png}
#!     \end{center}
#! </Alt>
#! <Alt Only="HTML"><![CDATA[<center><img height="450" src="sgp-P3-org.png"/></center>]]></Alt>
#! <Alt Not="LaTeX HTML">Image of a Cayley graph not available in this medium.</Alt>
#!
#! <Alt Only="LaTeX">
#!     \begin{center}
#!         \includegraphics[height=2.4in]{sgp-P3-org-2.png}
#!     \end{center}
#! </Alt>
#! <Alt Only="HTML"><![CDATA[<center><img height="450" src="sgp-P3-org-2.png"/></center>]]></Alt>
#! <Alt Not="LaTeX HTML">Image of a Cayley graph not available in this medium.</Alt>
#!
#! @Subsection A full transformation semigroup
#!
#! @Example
#! P := DirectProduct(
#!     Semigroup( [ Transformation( [ 2, 3, 1 ] ) ] ), # group Z_3
#!     Semigroup( [ Transformation( [ 3, 5, 4, 2, 6, 3 ] ) ] ) # group Z_5
#! ); # group Z_3 x Z_5
#! ShowCayleyGraph( P, rec( ToString := compact ) );
#! @EndExample
#!
#! This produces the disorganized initial image shown below.
#!
#! <Alt Only="LaTeX">
#!     \begin{center}
#!         \includegraphics[height=2.4in]{sgp-F3-unorg.png}
#!     \end{center}
#! </Alt>
#! <Alt Only="HTML"><![CDATA[<center><img height="450" src="sgp-F3-unorg.png"/></center>]]></Alt>
#! <Alt Not="LaTeX HTML">Image of a Cayley graph not available in this medium.</Alt>
#!
#! But we can make it more attractive by rearranging the vertices,
#! as shown in the following image.
#!
#! <Alt Only="LaTeX">
#!     \begin{center}
#!         \includegraphics[height=3.5in]{sgp-F3-org.png}
#!     \end{center}
#! </Alt>
#! <Alt Only="HTML"><![CDATA[<center><img height="650" src="sgp-F3-org.png"/></center>]]></Alt>
#! <Alt Not="LaTeX HTML">Image of a Cayley graph not available in this medium.</Alt>
